# -*- coding: utf-8 -*-
"""(Global) Suicide rate per 100k pop by age group

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CLeWi4XiRuFZvvVBD3F8yZ9dYqqCuv_1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pylab

from google.colab import files
uploaded = files.upload()

import io
df = pd.read_csv(io.BytesIO(uploaded['master.csv']))
# Dataset is now stored in a Pandas Dataframe

#melting male and female entries that have the same year, averaging their suicide_no
df2 = df.pivot_table(index='age',
                             columns='year',
                             values='suicides/100k pop', aggfunc=np.average)

#Dividing by age groups
youngest = df2.loc['5-14 years', :].values.tolist()
teen = df2.loc['15-24 years', :].values.tolist()
adult = df2.loc['25-34 years', :].values.tolist()
middle = df2.loc['35-54 years', :].values.tolist()
older = df2.loc['55-74 years', :].values.tolist()
senior = df2.loc['75+ years', :].values.tolist()

year = [1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016]

plt.plot(year, youngest, color='yellow', label='5-14')
plt.plot(year, teen, color='orange',label='15-24')
plt.plot(year, adult, color='green', label='25-34')
plt.plot(year, middle, color='blue',label = '35-54')
plt.plot(year, older, color='black',label='55-74')
plt.plot(year, senior, color='grey',label='75+')

plt.xlabel('Year')
plt.ylabel('No. Suicides/100k pop.')
plt.title('Avg # of suicides per 100k pop. for different age groups from 1985-2016')
pylab.legend(loc='upper left')
plt.show()