# -*- coding: utf-8 -*-
"""Joint Set

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A3HEFK9RToax7XO3g9VSrjS-TvzUE8YI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pylab
import csv
import os

from google.colab import files


import io

df1 = pd.read_csv("joinedkaggledata.csv")
df2 = pd.read_csv("all.csv")

#initialize the new regional columns to be added
df1['region'] = 'N/A'
df1['sub-region'] = 'N/A'

#rename all.csv's 'name' column to 'country' 
df2.rename(columns={'name':'country'}, inplace=True)

#merge columns on country
mergedStuff = pd.merge(df1, df2, on=['country'], how='inner')

#dropping uneeded/unusable columns: only a few entries have intermideate region values
mergedStuff.drop(columns = ['alpha-2','alpha-3','country-code', 'iso_3166-2', 'region_x', 'sub-region_x', 'intermediate-region'], inplace = True)

mergedStuff.to_csv('merged.csv')
files.download('merged.csv')

